### ISSUE TITLE
Crash when launching with Slight GUI Modifications mod

### ISSUE THREAD

**Issue by floral-qua-floral** [Leo40Git/Duravision#1]
When launching the game with both Duravision and the ['Slight' GUI Modifications](https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications) mod, the game fails to launch and a crash report will not be generated. I'm using Duravision 0.2.0 and Fabric 0.8.3, build.196. The launcher gives a popup that says a crash has occurred but provides no further details. The issue seems to occur even if neither mod has a config.

Potentially important note - SGM's latest release at the time of writing, 0.4.0, seems to have its own crash-on-startup issue unrelated to this incompatibility. To test the two mods together, I'd recommend using SGM 0.3.0, which is able to launch without issue on its own (and displays the issue described in this report when launched alongside Duravision).

**Comment by Leo40Git** [comment]
You'd think it'd be because my "Improved Potion Overlay" and shed's "Fluid Potion Effects" features are conflicting, but you said they happen when neither mods have a config, and shed's feature is disabled by default.
Anyway,
>Fabric 0.8.3, build.196
please update your Fabric version (we're on 0.10 now) and test this again, this might just be a loader/API bug that's been already fixed.

**Comment by floral-qua-floral** [comment]
Oh, my mistake! I was referring to Fabric loader's version, not Fabric API's version. 0.8.3 build 196 is the latest Fabric loader version available from the installer, I just updated earlier today. The version of Fabric API I am and was using is 0.10.8, build 310 - latest version, as you mentioned.

Just went and double-checked the configs, and yup, it definitely still occurs when I've made sure there're no config files for either mod, which is strange.

**Comment by Leo40Git** [comment]
Hm. Try disabling my mod's potion overlay changes? I'll look into this on my side as well.

**Comment by floral-qua-floral** [comment]
Oh, good call, I didn't think to try that. Still crashing after setting "replace_vanilla_potion_overlay" to false, though. I went and disabled the other config entries just on the off-chance one of them might do something, but no results there either.

Good news, though - I've just discovered that while it doesn't generate any crash reports, it _does_ generate a log! Here's the log from attempting to launch with just Fabric API, Slight GUI Modifications, and Duravision (all config values false):
[latest.log](https://github.com/Leo40Git/Duravision/files/4647751/latest.log)

**Comment by Leo40Git** [comment]
...who mixins into DrawableHelper of all things? Right, just gotta make Duravision load after SGM, i think.

**Comment by Leo40Git** [comment]
Please send `debug.log` as well (should be in either the "logs" or "crash-reports" folders).

**Comment by Leo40Git** [comment]
ok apparently I did a very bad and loaded *way* more classes than I thought I would, fixed in latest commit
I'll make a 0.3 release since i also added some new features as well

**Comment by Leo40Git** [comment]
0.3 is out and should no longer have this issue.
